apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: {{ .Values.appName }}
spec:
  accessModes:
    - {{ .Values.volume.mysql.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.mysql.size }}
