apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.secret.name }}
  namespace: webapp
spec:
  encryptedData:
    password: AgBqsL3HX/XUdMBg+rpO/GiCUQd0bQ7TzzploNS8QQpPm/NvzQAUCf+sjumN0QCwTZT0w//lrHY/wGdkIp0U49g+6MeBroegjk5dEUOsQr+Ip2FYhR5MfuppQyuQ0jM9Upsnqca4uuVtgTx/2G4cna53sag9bqXJfwkpbphY2yMd3kOL1O4o7fypjK/hb4Gu+1dnOq9GBzwwumgA/IeswADChjKSQ+2eRy8IHUJlE/TWwP6lRxoApNqw3qcuAPUr3gW76hD9sxntLW2QgDr0+6lOVSmnv5V5osW8zBewTAlEJeNLXySRDPM/w+qTI0p/8zp6pfv00kX68EmUaHPZ6jOT6XZwGBIFYVAF2lVr+9GBQKWCmWWRN81Gsg7zGAX5HAbpkLcsF7890MqVQceGQpN2Exyx9jwuMgQDM3CP0IWbPEFv32BFiOJLAQwQZrjnwh+KuCmBvDSdNsdNkNf3OPQ7MCVDUYq+7N64d2wpr996OYhgc2aMEinzXy2GdcNtJRDCFldf2e2d75EAPvNyKKmCOouPjTFmMDKdt2rqVQjXJKVs4xQY+NsUO5XRE0ynAoYKiKCf0B9zl2uC9iO4lbuogo+d224Gjg+o1nn8Wmx3qpqZqbufIeIQ4nQsNdCSFZbGSRrPubJOEolFMaiRoWznSsJwH901nFLO0CZu/2BfP3EP+UVBfi0WRBnR3NKsG16MTxTx7z17
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.secret.name }}
      namespace: webapp
