apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-password
  namespace: webapp
spec:
  encryptedData:
    secret: AgAdcPFhmVT8phG/T7DyAqzCwVxr8F2zH95TEtg0rqpjNgC2QGrhsX8dmhttRuoMDEQ8pRGpxAV2j8pQxuGHPCFMCR1vcP0NoVmQ/H8NAUgOq3vaMfykBUvquQ5rBqdjhqD3WTNoLWm8jEt01+tt8SBjCdYOApuqctWGU4sWEkR+c7PoJNeUZ1PJECRoRUowxOCZXgz+S0HALUkTquvCrxOWwG6ilNmkEI/KmNyBjr2nqIe/oDzVTFUh8oARUs9S49M9cdjEhzGLITYRehy2zrHlqhfyVrzxnpA08qWCIyfM/rVwYlr2+GsK/dwd1Bp5/hZrRSjqP+EWLOhX1wbaNYrKQiR6wK7L2jScVCc4EeSx8IdpYBzeOQ6AQABu5xIWITNDIJ4IqQxTG7VHRfaUlnee+2XPz2Cq2qY1g+jX6VJtm8d32z6Aa1GJqgeHo3MmKy9yubi2e+OpahkIgiKBhazYJB3FQWYG9szkUOK6QHbWA94erGyjT0M1oeVDp2eTuJsgbTyZ1bzqiVxHMlj9SwA6rxJ4nqYKzd6/2FFycB+Saw0v5ybwxE/B/b0b7JOat7Qns6d2ACfYNjIX6BzjFRhYOZ6gg6AWNu8XBOK7JhVaeD9wvi70fsRT1zIMkE/bxEZEuAZ5TWE2Cx9xDya3j0aKEfB646oS3dcDJweV9Nbrmj0qlpHxJ2lZEMH7HVLt4cXRziLdqCSK
  template:
    metadata:
      creationTimestamp: null
      name: mysql-password
      namespace: webapp
