apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-password
  namespace: webapp
spec:
  template:
    metadata:
      name: mysql-password
      namespace: webapp
  encryptedData:
    password: AgCtfiyFwgnFSr0FeMr8ZcFyL2p9/u6hpEXIy6wUVWzD6xFhfYLyf3GMkLZ+8FehSUSbduYUWOZ4+jWajNw2LN3mBZoIm0KE2jkOGiM7DQ+ZIB98X3zGbXRqTZA7OKy+APwgKyWH2iZzUybkBeu3p0SdHNGrGxU/Xvq763gTJf9aIvHf43Oj71u04p4c/YJOOGDyzCvxJLtj9IglGb/eHQpGVvVL1bwhOy9d5YUDT/vRa0ofwktv/MCZa2wS4O4mhZ6O4DHFIpe+XTCMjQVzGdNkxMIe/9fBsP/+8Ut2gUqMSV8Kqyb4LmgAfeWYBPghuFjHSb8e0N5zx4ObaO5j8HL9wXAHuFUvGBfLX53esKy/dprwbZirL1Ivm053tGeSkh/pNjIT161cQ7clqgybrws7N/KoINDct5MXc6oQ3pEO/fDO3DJPyoK9izpjJKlHl5BcEqFgfCo8CZcB6luz6Hv3lLHg1Scp+yleGYrHm35WdPmwM0wzwCoxBL86xGwm2+tUMKYrGZS+kGCPmlmaxTz4FXaObcGK9IXsb2tbfg9np4bWD41pvo0cG/Rc2/LhqSArqAyVKYq8eVGWwRLNjaP0fRvXy7r9rtfsxoudihW+HDls5Cpaj9nKS/I6tZoAlOidt6e8hET2a3t2lOew0olQjoXIwhbDtnzNmK0tZjkMwVkCY1bv69ElMiuomwfnjceCLAbr98s9gQ==
