apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-password
spec:
  template:
    metadata:
      name: mysql-password
  encryptedData:
    password: AgAVbQD8FCbnOvVCS+4NRJkUim4hrpNVMXn6MKuT7ITp9RsG5j7yC0ofEjJ1ajXmIPFS6AFGDpNuGf3HUsMvbXSmi385ak1c9zX7kbTHScIx7Jc/MlEJNXCeUq7YAwUVnbEwbQxbJ33cCx2ziFabonAqYoPfGSCwDSOfdLiZUdaVfpGhwN9kmeHexo+NSgqSCZiEYwmzJFnF6U2qd9wVK+OhWc324ONY+n9gUvJ00sDsoxxyk6uorBpYr8EndMHJOoZvTr70j90A4WCZhnnH0mfeUBk0fudEO1ZZqfyTmtH5DasRoTO/q/B1kJEqtWNQkfVn/tSJ5KcLeQYJFgPsH2f7Mw0K9nx57fFuSLKPavd26771ziCj4waKcPXIooxC39v3ZINrO1ZPrSKEODakXihaVijVk45WyUpYZ1ZJqRTWY+CngLBpn+VZAdE3iIvo77w4m3APWoPJuI1ZHLzIwTu1nRRtHh1toqkmkNWTsSVtxqiUooIAyzfuWnYyb1bJGSS9vPKrNuoHwBErTQ/HjmKzaJwblGWIv04c3L7V1c3A/dmxjv2qreAH633AyAt4817Af0HviD6jA1JMJsLidrZ8xFKwC3DItxoPemEBWsXrDL5Ffom+cferTazKaA7RX7e5TFPubsTPmBAsPcWgZppKhLbKl616+h+ICBInt9zNlLsnu1oMiPSY5oqttwaDUbTQJvmKn9vY+Q==
