apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: ClusterIP
