apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Values.appName }}
    tier: mysql
  clusterIP: None